@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Setup  [self-unpacking]
rem  Generated by Venv Batch Template Generator (Leon Priest / 7h3v01d) v3.4.0
rem  Generated on: 2026-07-11 10:53
rem
rem  Ship ONLY this file in your repo.  On first run it:
rem    1. Checks Python
rem    2. Creates / verifies the virtual environment
rem    3. Installs dependencies
rem    4. Writes companion scripts beside this file:
rem       run.bat  pip.bat  shell.bat  sync.bat  doctor.bat  test.bat
rem
rem  Companion scripts are NOT overwritten if they already exist.
rem  Add them to .gitignore to keep your repo tidy.
rem ============================================================

set "PROJECT_NAME=program_inventory"
set "VENV_DIR=.venv"

title "%PROJECT_NAME% - SETUP"

echo ============================================================
echo  Setup: %PROJECT_NAME%
echo ============================================================
echo.

rem ── 1. Environment check + venv bootstrap ───────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not on PATH.
    echo.
    echo Install Python from https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [INFO] Virtual environment already exists at "%VENV_DIR%\"
    echo        Skipping creation.
    echo.
) else (
    echo [1/3] Creating virtual environment...
    echo ============================================================
    python -m venv "%VENV_DIR%"
    if errorlevel 1 ( echo [ERROR] venv creation failed. & pause & exit /b 1 )
    echo.

    echo [2/3] Upgrading pip...
    echo ============================================================
    "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo.

    if exist "requirements.txt" (
        echo [3/3] Installing dependencies from requirements.txt...
        echo ============================================================
        "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
        echo.
    ) else (
        echo [3/3] SKIPPED: No requirements.txt found.
        echo        Run sync.bat after adding dependencies.
        echo.
    )
)

rem ── 2. Write companion scripts ───────────────────────────────
echo ============================================================
echo  Writing companion scripts...
echo ============================================================
echo.

rem ── run.bat ─────────────────────────────────────────────────
set "OUTFILE=run.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_run_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbCBFbmFibGVEZWxheWVkRXhwYW5zaW9uDQpjZCAvZCAiJX5kcDAi
        echo DQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCBSdW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYg
        echo QmF0Y2ggVGVtcGxhdGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0K
        echo cmVtICBHZW5lcmF0ZWQgb246IDIwMjYtMDctMTEgMTA6NTMNCnJlbQ0KcmVtICBFTlRSWV9NT0RF
        echo Og0KcmVtICAgIGZpbGUgICAtPiBweXRob24gYXBwLnB5DQpyZW0gICAgbW9kdWxlIC0+IHB5dGhv
        echo biAtbSBwYWNrYWdlLm1vZHVsZQ0KcmVtICAgIHJ1bm5lciAtPiBweXRob24gLW0gcnVubmVyX21v
        echo ZHVsZSBbYXJncy4uLl0NCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNUX05BTUU9cHJvZ3JhbV9pbnZl
        echo bnRvcnkiDQpzZXQgIlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJFTlRSWV9NT0RFPW1vZHVsZSINCnNl
        echo dCAiQVBQX0VOVFJZPXByb2dyYW1faW52ZW50b3J5Ig0Kc2V0ICJSVU5ORVJfQVJHUz0iDQoNCnNl
        echo dCAiUFk9JUNEJVwlVkVOVl9ESVIlXFNjcmlwdHNccHl0aG9uLmV4ZSINCg0KaWYgbm90IGV4aXN0
        echo ICIlUFklIiAoDQogICAgZWNobyBbRVJST1JdIExvY2FsIHZlbnYgbm90IGZvdW5kOiAiJVBZJSIN
        echo CiAgICBlY2hvLg0KICAgIGVjaG8gRml4IHdpdGg6DQogICAgZWNobyAgIHB5dGhvbiAtbSB2ZW52
        echo ICIlVkVOVl9ESVIlIg0KICAgIGVjaG8gICAiJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUi
        echo IC1tIHBpcCBpbnN0YWxsIC0tdXBncmFkZSBwaXANCiAgICBlY2hvICAgIiVWRU5WX0RJUiVcU2Ny
        echo aXB0c1xweXRob24uZXhlIiAtbSBwaXAgaW5zdGFsbCAtciByZXF1aXJlbWVudHMudHh0DQogICAg
        echo ZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0KDQppZiAvSSAiJUVOVFJZX01PREUl
        echo Ij09ImZpbGUiIGlmIG5vdCBleGlzdCAiJUFQUF9FTlRSWSUiICgNCiAgICBlY2hvIFtFUlJPUl0g
        echo RW50cnkgZmlsZSBub3QgZm91bmQ6ICIlQVBQX0VOVFJZJSINCiAgICBlY2hvIEVkaXQgcnVuLmJh
        echo dCBvciBydW4gd2l0aCB0aGUgY29ycmVjdCBlbnRyeSBmaWxlLg0KICAgIHBhdXNlDQogICAgZXhp
        echo dCAvYiAxDQopDQoNCnRpdGxlICIlUFJPSkVDVF9OQU1FJSAtIFJVTiINCmVjaG8gPT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hv
        echo ICBSdW5uaW5nIDogJVBST0pFQ1RfTkFNRSUNCmVjaG8gIFByb2plY3QgOiAlQ0QlDQplY2hvICBQ
        echo eXRob24gIDogJVBZJQ0KZWNobyAgTW9kZSAgICA6ICVFTlRSWV9NT0RFJQ0KZWNobyAgRW50cnkg
        echo ICA6ICVBUFBfRU5UUlklDQppZiAvSSAiJUVOVFJZX01PREUlIj09InJ1bm5lciIgZWNobyAgQXJn
        echo cyAgICA6ICVSVU5ORVJfQVJHUyUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvLg0KDQpzZXQgIkVYSVRDT0RFPTAi
        echo DQoNCmlmIC9JICIlRU5UUllfTU9ERSUiPT0ibW9kdWxlIiAoDQogICAgIiVQWSUiIC1tICVBUFBf
        echo RU5UUlklICUqDQopIGVsc2UgaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJydW5uZXIiICgNCiAgICBp
        echo ZiBkZWZpbmVkIFJVTk5FUl9BUkdTICgNCiAgICAgICAgIiVQWSUiIC1tICVBUFBfRU5UUlklICFS
        echo VU5ORVJfQVJHUyEgJSoNCiAgICApIGVsc2UgKA0KICAgICAgICAiJVBZJSIgLW0gJUFQUF9FTlRS
        echo WSUgJSoNCiAgICApDQopIGVsc2UgKA0KICAgICIlUFklIiAiJUFQUF9FTlRSWSUiICUqDQopDQoN
        echo CnNldCAiRVhJVENPREU9IUVSUk9STEVWRUwhIg0KDQplY2hvLg0KZWNobyA9PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFBy
        echo b2Nlc3MgZXhpdGVkIHdpdGggY29kZTogIUVYSVRDT0RFIQ0KZWNobyA9PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnBhdXNlDQpleGl0
        echo IC9iICFFWElUQ09ERSENCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── pip.bat ─────────────────────────────────────────────────
set "OUTFILE=pip.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_pip_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QtbG9jYWwgcGlwIHdyYXBwZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxh
        echo dGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0
        echo ZWQgb246IDIwMjYtMDctMTEgMTA6NTMNCnJlbQ0KcmVtICBVc2FnZToNCnJlbSAgICBwaXAuYmF0
        echo IGluc3RhbGwgcmVxdWVzdHMNCnJlbSAgICBwaXAuYmF0IGluc3RhbGwgLXIgcmVxdWlyZW1lbnRz
        echo LnR4dA0KcmVtICAgIHBpcC5iYXQgZnJlZXplID4gcmVxdWlyZW1lbnRzLnR4dA0KcmVtICAgIHBp
        echo cC5iYXQgbGlzdA0KcmVtICAgIHBpcC5iYXQgdW5pbnN0YWxsIHJlcXVlc3RzDQpyZW0gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQoN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5
        echo dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2Nh
        echo bCB2ZW52IHdhcyBub3QgZm91bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8u
        echo DQogICAgZWNobyBDcmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZl
        echo bnYgIiVWRU5WX0RJUiUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0K
        echo DQoiJVBZJSIgLW0gcGlwICUqDQpleGl0IC9iICVFUlJPUkxFVkVMJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── shell.bat ─────────────────────────────────────────────────
set "OUTFILE=shell.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_shell_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpjZCAvZCAiJX5kcDAiDQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCB2ZW52IHNo
        echo ZWxsDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRvciAoTGVv
        echo biBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2LTA3LTEx
        echo IDEwOjUzDQpyZW0NCnJlbSAgT3BlbnMgYW4gYWN0aXZhdGVkIENNRCBzZXNzaW9uIGZvciB0aGlz
        echo IHByb2plY3QuDQpyZW0gIFVzZSBvbmx5IHdoZW4geW91IG5lZWQgYW4gaW50ZXJhY3RpdmUgdmVu
        echo diBzZXNzaW9uLg0KcmVtICBFeGl0IHdpdGg6IGV4aXQNCnJlbSA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNU
        echo X05BTUU9cHJvZ3JhbV9pbnZlbnRvcnkiDQpzZXQgIlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJBQ1RJ
        echo VkFURT0lQ0QlXCVWRU5WX0RJUiVcU2NyaXB0c1xhY3RpdmF0ZS5iYXQiDQoNCmlmIG5vdCBleGlz
        echo dCAiJUFDVElWQVRFJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2NhbCB2ZW52IHdhcyBub3QgZm91
        echo bmQ6DQogICAgZWNobyAgICAgICAgICIlQUNUSVZBVEUlIg0KICAgIGVjaG8uDQogICAgZWNobyBD
        echo cmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZlbnYgIiVWRU5WX0RJ
        echo UiUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0KDQp0aXRsZSAiJVBS
        echo T0pFQ1RfTkFNRSUgLSBWRU5WIFNIRUxMIg0KY2FsbCAiJUFDVElWQVRFJSINCg0KZWNobyA9PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0N
        echo CmVjaG8gIFByb2plY3Qgc2hlbGwgYWN0aXZhdGVkDQplY2hvICBQcm9qZWN0OiAiJUNEJSINCmVj
        echo aG8gIFB5dGhvbiA6DQp3aGVyZSBweXRob24NCmVjaG8gIFR5cGUgImV4aXQiIHRvIGxlYXZlIHRo
        echo aXMgc2hlbGwuDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PQ0KZWNoby4NCmNtZCAvaw0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── sync.bat ─────────────────────────────────────────────────
set "OUTFILE=sync.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_sync_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIERlcGVu
        echo ZGVuY3kgU3luYyAocGlwKQ0KcmVtICBHZW5lcmF0ZWQgYnkgVmVudiBCYXRjaCBUZW1wbGF0ZSBH
        echo ZW5lcmF0b3IgKExlb24gUHJpZXN0IC8gN2gzdjAxZCkgdjMuNC4wDQpyZW0gIEdlbmVyYXRlZCBv
        echo bjogMjAyNi0wNy0xMSAxMDo1Mw0KcmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1wcm9ncmFt
        echo X2ludmVudG9yeSINCnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElS
        echo JVxTY3JpcHRzXHB5dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8g
        echo W0VSUk9SXSBMb2NhbCB2ZW52IG5vdCBmb3VuZDogIiVQWSUiDQogICAgZWNoby4NCiAgICBlY2hv
        echo IENyZWF0ZSBpdCB3aXRoOg0KICAgIGVjaG8gICBweXRob24gLW0gdmVudiAiJVZFTlZfRElSJSIN
        echo CiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0KDQp0aXRsZSAiJVBST0pFQ1RfTkFNRSUgLSBT
        echo WU5DIg0KDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PQ0KZWNobyAgU3luY2luZzogJVBST0pFQ1RfTkFNRSUNCmVjaG8gIFB5
        echo dGhvbiA6ICVQWSUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQplY2hvLg0KDQplY2hvIFsxLzNdIFVwZ3JhZGluZyBwaXAu
        echo Li4NCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09DQoiJVBZJSIgLW0gcGlwIGluc3RhbGwgLS11cGdyYWRlIHBpcA0KZWNoby4N
        echo Cg0KaWYgZXhpc3QgInJlcXVpcmVtZW50cy50eHQiICgNCiAgICBlY2hvIFsyLzNdIEluc3RhbGxp
        echo bmcgZnJvbSByZXF1aXJlbWVudHMudHh0Li4uDQogICAgZWNobyA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCiAgICAiJVBZJSIgLW0g
        echo cGlwIGluc3RhbGwgLXIgcmVxdWlyZW1lbnRzLnR4dA0KICAgIGVjaG8uDQopIGVsc2UgKA0KICAg
        echo IGVjaG8gWzIvM10gU0tJUFBFRDogTm8gcmVxdWlyZW1lbnRzLnR4dCBmb3VuZC4NCiAgICBlY2hv
        echo ICAgICAgIENyZWF0ZSBvbmUgd2l0aDogcGlwLmJhdCBmcmVlemUgXj4gcmVxdWlyZW1lbnRzLnR4
        echo dA0KICAgIGVjaG8uDQopDQoNCmVjaG8gWzMvM10gRGVwZW5kZW5jeSBoZWFsdGggY2hlY2suLi4N
        echo CmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09DQoiJVBZJSIgLW0gcGlwIGNoZWNrDQplY2hvLg0KDQplY2hvID09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAg
        echo U1lOQyBDT01QTEVURQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCnBhdXNlDQpleGl0IC9iIDANCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── doctor.bat ─────────────────────────────────────────────────
set "OUTFILE=doctor.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_doctor_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgRG9jdG9yDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRv
        echo ciAoTGVvbiBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2
        echo LTA3LTExIDEwOjUzDQpyZW0gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQoNCnNldCAiUFJPSkVDVF9OQU1FPXByb2dyYW1faW52ZW50
        echo b3J5Ig0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiRU5UUllfTU9ERT1tb2R1bGUiDQpzZXQg
        echo IkFQUF9FTlRSWT1wcm9ncmFtX2ludmVudG9yeSINCnNldCAiUlVOTkVSX0FSR1M9Ig0Kc2V0ICJQ
        echo WT0lQ0QlXCVWRU5WX0RJUiVcU2NyaXB0c1xweXRob24uZXhlIg0KDQplY2hvID09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAg
        echo UFJPSkVDVCBET0NUT1I6ICVQUk9KRUNUX05BTUUlDQplY2hvID09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgUHJvamVjdCA6
        echo ICVDRCUNCmVjaG8gIE1vZGUgICAgOiAlRU5UUllfTU9ERSUNCmVjaG8gIEVudHJ5ICAgOiAlQVBQ
        echo X0VOVFJZJQ0KaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJydW5uZXIiIGVjaG8gIEFyZ3MgICAgOiAl
        echo UlVOTkVSX0FSR1MlDQplY2hvLg0KDQppZiBub3QgZXhpc3QgIiVQWSUiICgNCiAgICBlY2hvIFtG
        echo QUlMXSB2ZW52IG5vdCBmb3VuZCBhdDogIiVQWSUiDQogICAgZWNoby4NCiAgICBlY2hvIENyZWF0
        echo ZSBpdCB3aXRoOg0KICAgIGVjaG8gICBweXRob24gLW0gdmVudiAiJVZFTlZfRElSJSINCiAgICBw
        echo YXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0KDQplY2hvIFtPS10gdmVudiBmb3VuZDogIiVQWSUiDQpl
        echo Y2hvLg0KDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLQ0KZWNobyAgUHl0aG9uIEVudmlyb25tZW50DQplY2hvIC0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KIiVQ
        echo WSUiIC1jICJpbXBvcnQgc3lzOyBwcmludCgnRXhlY3V0YWJsZSA6Jywgc3lzLmV4ZWN1dGFibGUp
        echo OyBwcmludCgnVmVyc2lvbiAgICA6Jywgc3lzLnZlcnNpb24uc3BsaXQoKVswXSk7IHByaW50KCdQ
        echo cmVmaXggICAgIDonLCBzeXMucHJlZml4KSINCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBwaXAg
        echo dmVyc2lvbg0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0NCiIlUFklIiAtbSBwaXAgLS12ZXJzaW9uDQplY2hvLg0KDQplY2hv
        echo IC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLQ0KZWNobyAgSW5zdGFsbGVkIFBhY2thZ2VzDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KIiVQWSUiIC1tIHBpcCBs
        echo aXN0DQplY2hvLg0KDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KZWNobyAgRGVwZW5kZW5jeSBIZWFsdGgNCmVjaG8gLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo DQoiJVBZJSIgLW0gcGlwIGNoZWNrDQplY2hvLg0KDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KZWNobyAgRW50cnkgUG9p
        echo bnQgQ2hlY2sNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tDQppZiAvSSAiJUVOVFJZX01PREUlIj09ImZpbGUiICgNCiAgICBp
        echo ZiBleGlzdCAiJUFQUF9FTlRSWSUiICgNCiAgICAgICAgZWNobyBbT0tdIEVudHJ5IGZpbGUgZm91
        echo bmQ6ICIlQVBQX0VOVFJZJSINCiAgICApIGVsc2UgKA0KICAgICAgICBlY2hvIFtGQUlMXSBFbnRy
        echo eSBmaWxlIE5PVCBmb3VuZDogIiVBUFBfRU5UUlklIg0KICAgICkNCikgZWxzZSAoDQogICAgIiVQ
        echo WSUiIC1jICJpbXBvcnQgaW1wb3J0bGliLnV0aWwsIHN5czsgbmFtZT1yJyVBUFBfRU5UUlklJzsg
        echo c3BlYz1pbXBvcnRsaWIudXRpbC5maW5kX3NwZWMobmFtZSk7IHByaW50KCgnW09LXSBNb2R1bGUg
        echo Zm91bmQ6ICcgaWYgc3BlYyBlbHNlICdbRkFJTF0gTW9kdWxlIE5PVCBmb3VuZDogJykgKyBuYW1l
        echo KTsgc3lzLmV4aXQoMCBpZiBzcGVjIGVsc2UgMSkiIDI+bnVsDQogICAgaWYgZXJyb3JsZXZlbCAx
        echo IGVjaG8gW0ZBSUxdIE1vZHVsZSBpbXBvcnQgdGVzdCBmYWlsZWQuDQogICAgaWYgL0kgIiVFTlRS
        echo WV9NT0RFJSI9PSJydW5uZXIiIGVjaG8gW0lORk9dIFJ1bm5lciBhcmdzOiAiJVJVTk5FUl9BUkdT
        echo JSINCikNCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBQcm9qZWN0IEZpbGVzDQplY2hvIC0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0K
        echo aWYgZXhpc3QgInV2LmxvY2siICAgICAgICAgIGVjaG8gW09LXSAgIHV2LmxvY2sgZm91bmQNCmlm
        echo IGV4aXN0ICJweXByb2plY3QudG9tbCIgICBlY2hvIFtPS10gICBweXByb2plY3QudG9tbCBmb3Vu
        echo ZA0KaWYgZXhpc3QgInJlcXVpcmVtZW50cy50eHQiIGVjaG8gW09LXSAgIHJlcXVpcmVtZW50cy50
        echo eHQgZm91bmQNCmlmIG5vdCBleGlzdCAicmVxdWlyZW1lbnRzLnR4dCIgZWNobyBbV0FSTl0gcmVx
        echo dWlyZW1lbnRzLnR4dCBtaXNzaW5nDQplY2hvLg0KDQplY2hvID09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgRE9DVE9SIENP
        echo TVBMRVRFDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PQ0KcGF1c2UNCmV4aXQgL2IgMA0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── test.bat ─────────────────────────────────────────────────
set "OUTFILE=test.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_test_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgdGVzdCBydW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxhdGUgR2Vu
        echo ZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0ZWQgb246
        echo IDIwMjYtMDctMTEgMTA6NTMNCnJlbQ0KcmVtICBSdW5zIHB5dGVzdCB2aWEgdGhlIHByb2plY3Qt
        echo bG9jYWwgdmVudiBQeXRob24uDQpyZW0NCnJlbSAgVXNhZ2U6DQpyZW0gICAgdGVzdC5iYXQgICAg
        echo ICAgICAgICAgICAgICAgICAgICAocnVuIGFsbCB0ZXN0cykNCnJlbSAgICB0ZXN0LmJhdCB0ZXN0
        echo cy90ZXN0X2NvcmUucHkgICAgIChydW4gYSBzcGVjaWZpYyBmaWxlKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC1rIG1hcHBlciAgICAgICAgICAgICAgKGZpbHRlciBieSBuYW1lKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC12IC0tdGI9c2hvcnQgICAgICAgICAgKHZlcmJvc2Ugd2l0aCBzaG9ydCB0cmFjZWJhY2tzKQ0K
        echo cmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1wcm9ncmFtX2ludmVudG9yeSINCnNldCAiVkVO
        echo Vl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUi
        echo DQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2NhbCB2ZW52IHdh
        echo cyBub3QgZm91bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8uDQogICAgcGF1
        echo c2UNCiAgICBleGl0IC9iIDENCikNCg0KdGl0bGUgIiVQUk9KRUNUX05BTUUlIC0gVEVTVCINCmVj
        echo aG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09DQplY2hvICBUZXN0aW5nOiAiJVBST0pFQ1RfTkFNRSUiDQplY2hvICBQeXRob24gOiAi
        echo JVBZJSINCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09DQplY2hvLg0KIiVQWSUiIC1tIHB5dGVzdCAtdiAlKg0Kc2V0ICJFWElU
        echo Q09ERT0lRVJST1JMRVZFTCUiDQoNCmVjaG8uDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KaWYgIiVFWElUQ09ERSUiPT0i
        echo MCIgKA0KICAgIGVjaG8gIFRFU1RTIFBBU1NFRA0KKSBlbHNlICgNCiAgICBlY2hvICBURVNUUyBG
        echo QUlMRUQgIF4oZXhpdCBjb2RlOiAlRVhJVENPREUlXikNCikNCmVjaG8gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpwYXVzZQ0KZXhp
        echo dCAvYiAlRVhJVENPREUlDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

echo.
echo ============================================================
echo  SETUP COMPLETE
echo.
echo  Companion scripts written (existing files were NOT overwritten).
echo  Add them to .gitignore to keep your repo tidy.
echo.
echo  Next steps:
echo    run.bat    - Launch %PROJECT_NAME%
echo    sync.bat   - Reinstall / update dependencies
echo    shell.bat  - Open activated venv shell
echo    doctor.bat - Environment health check
echo    pip.bat    - Project-local pip wrapper
echo    test.bat   - Run pytest suite
echo ============================================================
pause
exit /b 0
